from django.urls import path, include
from .views import (TheoryCreateView,
                    TheoriesListView,
                    TheoryDetailView,
                    ConceptCreateView,
                    TheoryUpdateView,
                    TheoriesDeleteView,
                    TheoryConceptCreate,
                    link_concepts,
                    ConceptUpdateView,
                    ConceptLinkDeleteView,
                    ConceptsListView,
                    ConceptComponent,
                    ComponentsListView,
                    ComponentLinkDeleteView,
                    ComponentUpdateView,
                    ConceptComponentCreate,
                    ConceptsListAllView,
                    ConceptsDeleteView,
                    ConceptReferencedView,
                    TreeListView)
from .apiViews import link_theory_concept_create, link_concept_component_create, ManageBreadCrumbs

urlpatterns = [
    path('',TheoriesListView.as_view(),name='theories_home'),
    path('new/',TheoryCreateView.as_view(),name='theories_create'),
    path('<int:pk>/',TheoryDetailView.as_view(),name='theories_detail'),
    path('<int:pk>/update/', TheoryUpdateView.as_view(), name='theories_update'),
    path('<int:pk>/delete/', TheoriesDeleteView.as_view(), name='theories_delete'),
    path('concepts_list/',ConceptsListAllView.as_view(),name='concepts_list'),
    path('concepts/<int:pk>/delete/', ConceptsDeleteView.as_view(), name='concept_delete'),
    path('concept/new/',ConceptCreateView.as_view(),name='concepts_create'),
    path('concept/<int:pk>/update/<int:theory>/',ConceptUpdateView.as_view(),name='concepts_update'),
    path('theory_concept/<int:pk>/',TheoryConceptCreate.as_view(),name='theory_concept'),
    path('link_concepts/<int:pk>/',ConceptsListView.as_view(),name='link_concepts'),
    path('link_concepts/link_concept_theory_create/',link_theory_concept_create,name='link_theory_concept_create'),
    path('concept_link_delete/<int:pk>/<int:theory>',ConceptLinkDeleteView.as_view(),name='concept_link_delete'),
    path('components/<int:pk>/<int:theory>/',ConceptComponent.as_view(),name='components_detail'),
    path('components/<int:pk>/link/<int:theory>/',ComponentsListView.as_view(),name='components_link'),
    path('components/<int:pk>/link/link_concept_component_create/',link_concept_component_create,name='link_concept_component_create'),
    path('component_link_delete/<int:pk>/<int:component>/<int:theory>',ComponentLinkDeleteView.as_view(),name='component_link_delete'),
    path('component/<int:pk>/update/<int:concept>/<int:theory>/',ComponentUpdateView.as_view(),name='components_update'),
    path('concept_component/<int:pk>/<int:theory>',ConceptComponentCreate.as_view(),name='concept_component'),
    path('concept/<int:pk>/referenced/',ConceptReferencedView.as_view(),name='concept_referenced'),
    path('treeview/<int:pk>/',TreeListView.as_view(),name='treeview'),
    path('breadcrumbs/',ManageBreadCrumbs.get_prev_crumb,name='breadcrumbs')
    ]