# Generated by Django 3.0.7 on 2020-06-16 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankCode', models.CharField(max_length=4)),
                ('BankName', models.CharField(max_length=30)),
                ('CentralBankFlag', models.BooleanField(default=False)),
                ('ReservePercent', models.FloatField()),
                ('ModelUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
