# Generated by Django 3.0.7 on 2020-06-25 02:50

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20200625_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='Deposits',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='AUD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='Loans',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='AUD', max_digits=14, null=True),
        ),
    ]
