# Generated by Django 3.0.7 on 2020-07-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_auto_20200704_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='Borrowings',
            new_name='LoanDeficit',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='Borrowings_currency',
            new_name='LoanDeficit_currency',
        ),
    ]
