# Generated by Django 3.0.7 on 2020-07-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTheory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.Theories')),
                ('sunTheory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTheory', to='theories.Theories')),
            ],
        ),
    ]
