# Generated by Django 3.0.7 on 2020-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0003_theories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepts',
            name='concept_description',
            field=models.TextField(default=''),
        ),
    ]
