# Generated by Django 3.0.7 on 2020-07-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0004_concepts_concept_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepts',
            name='concept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theories',
            name='theory',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TheoryConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.Concepts')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.Theories')),
            ],
        ),
    ]
