# Generated by Django 3.0.7 on 2020-08-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0008_auto_20200810_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeViewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('concept', models.CharField(max_length=50)),
                ('theory', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='theoryconcepts',
            name='theory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theories.Theories'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
