# Generated by Django 3.0.7 on 2020-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0009_auto_20200811_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeviewmodel',
            name='action',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
