# Generated by Django 3.0.7 on 2020-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0011_remove_treeviewmodel_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeviewmodel',
            name='action',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeviewmodel',
            name='prev_action',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
