# Generated by Django 3.0.7 on 2020-08-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0012_auto_20200812_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeviewmodel',
            old_name='prev_action',
            new_name='depth',
        ),
    ]
