# Generated by Django 3.0.7 on 2020-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0014_treeviewmodel_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeviewmodel',
            name='concept_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeviewmodel',
            name='father_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeviewmodel',
            name='parent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeviewmodel',
            name='theory_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
